// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AllOrders;
using ClassLibrary;
using System.Runtime.Serialization;

namespace AllOrders
{
    [DataContract]
    public class AddonValues2
    {
        public AddonValues2(string ccCvv, string ccExpires, string ccIssue, string ccNumber, string ccOwner, string ccStart, string ccType, string customerIp,
            string downloadAbandonmentStatus, string serviceAbandonmentStatus)
        {
            CcCvv = ccCvv;
            CcExpires = ccExpires;
            CcIssue = ccIssue;
            CcNumber = ccNumber;
            CcOwner = ccOwner;
            CcStart = ccStart;
            CcType = ccType;
            CustomerIp = customerIp;
            DownloadAbandonmentStatus = downloadAbandonmentStatus;
            ServiceAbandonmentStatus = serviceAbandonmentStatus;
        }

        [JsonProperty("ccCvv")]
        [DataMember]
        public string CcCvv { get; set; }

        [JsonProperty("ccExpires")]
        [DataMember]
        public string CcExpires { get; set; }

        [JsonProperty("ccIssue")]
        [DataMember]
        public string CcIssue { get; set; }

        [JsonProperty("ccNumber")]
        [DataMember]
        public string CcNumber { get; set; }

        [JsonProperty("ccOwner")]
        [DataMember]
        public string CcOwner { get; set; }

        [JsonProperty("ccStart")]
        [DataMember]
        public string CcStart { get; set; }

        [JsonProperty("ccType")]
        [DataMember]
        public string CcType { get; set; }

        [JsonProperty("customerIp")]
        [DataMember]
        public string CustomerIp { get; set; }

        [JsonProperty("downloadAbandonmentStatus")]
        [DataMember]
        public string DownloadAbandonmentStatus { get; set; }

        [JsonProperty("serviceAbandonmentStatus")]
        [DataMember]
        public string ServiceAbandonmentStatus { get; set; }
    }

}
