// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AllOrders;
using ClassLibrary;
using System.Runtime.Serialization;

namespace AllOrders
{
    [DataContract]
    public class Addresses
    {
        public Addresses(Customer2 customer, Billing billing, Delivery delivery)
        {
            Customer = customer;
            Billing = billing;
            Delivery = delivery;
        }

        [JsonProperty("customer")]
        [DataMember]
        public Customer2 Customer { get; set; }

        [JsonProperty("billing")]
        [DataMember]
        public Billing Billing { get; set; }

        [JsonProperty("delivery")]
        [DataMember]
        public Delivery Delivery { get; set; }
    }

}
