// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AllOrders;
using ClassLibrary;
using System.Runtime.Serialization;

namespace AllOrders
{
    [DataContract]
    public class Customer
    {
        public Customer(long id, string number, string email, string phone, string vatId, Status status)
        {
            Id = id;
            Number = number;
            Email = email;
            Phone = phone;
            VatId = vatId;
            Status = status;
        }
        [JsonProperty("id")]
        [DataMember]
        public long Id { get; set; }

        [JsonProperty("number")]
        [DataMember]
        public string Number { get; set; }

        [JsonProperty("email")]
        [DataMember]
        public string Email { get; set; }

        [JsonProperty("phone")]
        [DataMember]
        public string Phone { get; set; }

        [JsonProperty("vatId")]
        [DataMember]
        public string VatId { get; set; }

        [JsonProperty("status")]
        [DataMember]
        public Status Status { get; set; }
    }

}
