// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AllOrders;
using ClassLibrary;
using System.Runtime.Serialization;

namespace AllOrders
{
    [DataContract]
    public class Delivery
    {
        public Delivery(string gender, string firstname, string lastname, string company, string street, string houseNumber, string additionalAddressInfo, string suburb,
            string postcode, string city, long countryId, long zoneId, bool b2bStatus)
        {
            Gender = gender;
            Firstname = firstname;
            Lastname = lastname;
            Company = company;
            Street = street;
            HouseNumber = houseNumber;
            AdditionalAddressInfo = additionalAddressInfo;
            Suburb = suburb;
            Postcode = postcode;
            City = city;
            CountryId = countryId;
            ZoneId = zoneId;
            B2bStatus = b2bStatus;
        }

        [JsonProperty("gender")]
        [DataMember]
        public string Gender { get; set; }

        [JsonProperty("firstname")]
        [DataMember]
        public string Firstname { get; set; }

        [JsonProperty("lastname")]
        [DataMember]
        public string Lastname { get; set; }

        [JsonProperty("company")]
        [DataMember]
        public string Company { get; set; }

        [JsonProperty("street")]
        [DataMember]
        public string Street { get; set; }

        [JsonProperty("houseNumber")]
        [DataMember]
        public string HouseNumber { get; set; }

        [JsonProperty("additionalAddressInfo")]
        [DataMember]
        public string AdditionalAddressInfo { get; set; }

        [JsonProperty("suburb")]
        [DataMember]
        public string Suburb { get; set; }

        [JsonProperty("postcode")]
        [DataMember]
        public string Postcode { get; set; }

        [JsonProperty("city")]
        [DataMember]
        public string City { get; set; }

        [JsonProperty("countryId")]
        [DataMember]
        public long CountryId { get; set; }

        [JsonProperty("zoneId")]
        [DataMember]
        public long ZoneId { get; set; }

        [JsonProperty("b2bStatus")]
        [DataMember]
        public bool B2bStatus { get; set; }
    }

}
