// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AllOrders;
using ClassLibrary;
using System.Runtime.Serialization;

namespace AllOrders
{
    [DataContract]
    public class ShippingType
    {
        public ShippingType(string title, string module)
        {
            Title = title;
            Module = module;
        }

        [JsonProperty("title")]
        [DataMember]
        public string Title { get; set; }

        [JsonProperty("module")]
        [DataMember]
        public string Module { get; set; }
    }

}
