// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AllOrders;
using ClassLibrary;
using System.Runtime.Serialization;

namespace AllOrders
{
    [DataContract]
    public class StatusHistory
    {
        public StatusHistory(long id, long statusId, string dateAdded, string comment, bool customerNotified)
        {
            Id = id;
            StatusId = statusId;
            DateAdded = dateAdded;
            Comment = comment;
            CustomerNotified = customerNotified;
        }
        [JsonProperty("id")]
        [DataMember]
        public long Id { get; set; }

        [JsonProperty("statusId")]
        [DataMember]
        public long StatusId { get; set; }

        [JsonProperty("dateAdded")]
        [DataMember]
        public string DateAdded { get; set; }

        [JsonProperty("comment")]
        [DataMember]
        public string Comment { get; set; }

        [JsonProperty("customerNotified")]
        [DataMember]
        public bool CustomerNotified { get; set; }
    }

}
