// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AllOrders;
using ClassLibrary;
using System.Runtime.Serialization;

namespace AllOrders
{
    [DataContract]
    public class Status
    {
        public Status(long id, string name, string image, long discount, bool isGuest)
        {
            Id = id;
            Name = name;
            Image = image;
            Discount = discount;
            IsGuest = isGuest;
        }

        [JsonProperty("id")]
        [DataMember]
        public long Id { get; set; }

        [JsonProperty("name")]
        [DataMember]
        public string Name { get; set; }

        [JsonProperty("image")]
        [DataMember]
        public string Image { get; set; }

        [JsonProperty("discount")]
        [DataMember]
        public long Discount { get; set; }

        [JsonProperty("isGuest")]
        [DataMember]
        public bool IsGuest { get; set; }
    }

}
