// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AllOrders;
using ClassLibrary;
using System.Runtime.Serialization;

namespace AllOrders
{
    [DataContract]
    public class Total
    {
        public Total(long id, string title, long value, string valueText, string classs, long sortOrder)
        {
            Id = id;
            Title = title;
            Value = value;
            ValueText = valueText;
            Class = classs;
            SortOrder = sortOrder;
        }
        [JsonProperty("id")]
        [DataMember]
        public long Id { get; set; }

        [JsonProperty("title")]
        [DataMember]
        public string Title { get; set; }

        [JsonProperty("value")]
        [DataMember]
        public long Value { get; set; }

        [JsonProperty("valueText")]
        [DataMember]
        public string ValueText { get; set; }

        [JsonProperty("class")]
        [DataMember]
        public string Class { get; set; }

        [JsonProperty("sortOrder")]
        [DataMember]
        public long SortOrder { get; set; }
    }

}
