// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
    

namespace ClassLibrary
{
    public class OrderIn
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("statusId")]
        public int StatusId { get; set; }

        [JsonProperty("purchaseDate")]
        public string PurchaseDate { get; set; }

        [JsonProperty("currencyCode")]
        public string CurrencyCode { get; set; }

        [JsonProperty("languageCode")]
        public string LanguageCode { get; set; }

        [JsonProperty("comment")]
        public string Comment { get; set; }

        [JsonProperty("totalWeight")]
        public int TotalWeight { get; set; }

        [JsonProperty("paymentType")]
        public PaymentType2 PaymentType { get; set; }

        [JsonProperty("shippingType")]
        public ShippingType2 ShippingType { get; set; }

        [JsonProperty("customer")]
        public Customer2 Customer { get; set; }

        [JsonProperty("addresses")]
        public Addresses2 Addresses { get; set; }

        [JsonProperty("items")]
        public IList<Item> Items { get; set; }

        [JsonProperty("totals")]
        public IList<Total> Totals { get; set; }

        [JsonProperty("statusHistory")]
        public IList<StatusHistory2> StatusHistory { get; set; }

        [JsonProperty("addonValues")]
        public AddonValues3 AddonValues { get; set; }

        [JsonProperty("_links")]
        public IList<object> Links { get; set; }

    }
}
