// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ClassLibrary
{

        public class AddonValues2 : OrderIn
    {

            [JsonProperty("productId")]
            public string ProductId { get; set; }

            [JsonProperty("identifier")]
            public string Identifier { get; set; }
        }

}