// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ClassLibrary
{

        public class Status2 : OrderIn
        {

            [JsonProperty("id")]
            public int Id { get; set; }

            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("image")]
            public string Image { get; set; }

            [JsonProperty("discount")]
            public int Discount { get; set; }

            [JsonProperty("isGuest")]
            public bool IsGuest { get; set; }
        }

}
