// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ClassLibrary
{

        public class Item : OrderIn
        {

            [JsonProperty("id")]
            public int Id { get; set; }

            [JsonProperty("model")]
            public string Model { get; set; }

            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("quantity")]
            public int Quantity { get; set; }

            [JsonProperty("price")]
            public double Price { get; set; }

            [JsonProperty("finalPrice")]
            public double FinalPrice { get; set; }

            [JsonProperty("tax")]
            public int Tax { get; set; }

            [JsonProperty("isTaxAllowed")]
            public bool IsTaxAllowed { get; set; }

            [JsonProperty("discount")]
            public int Discount { get; set; }

            [JsonProperty("shippingTimeInformation")]
            public string ShippingTimeInformation { get; set; }

            [JsonProperty("checkoutInformation")]
            public string CheckoutInformation { get; set; }

            [JsonProperty("quantityUnitName")]
            public string QuantityUnitName { get; set; }

            [JsonProperty("attributes")]
            public IList<object> Attributes { get; set; }

            [JsonProperty("downloadInformation")]
            public IList<object> DownloadInformation { get; set; }

            [JsonProperty("addonValues")]
            public AddonValues2 AddonValues { get; set; }
        }

}
