// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ClassLibrary
{

        public class ShippingType2 : OrderIn
        {

            [JsonProperty("title")]
            public string Title { get; set; }

            [JsonProperty("module")]
            public string Module { get; set; }
        }

}