// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ClassLibrary
{

        public class Customer2 : OrderIn
    {

            [JsonProperty("id")]
            public int Id { get; set; }

            [JsonProperty("number")]
            public string Number { get; set; }

            [JsonProperty("email")]
            public string Email { get; set; }

            [JsonProperty("phone")]
            public string Phone { get; set; }

            [JsonProperty("vatId")]
            public string VatId { get; set; }

            [JsonProperty("status")]
            public Status2 Status { get; set; }
        }

}

