// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ClassLibrary
{

        public class Total : OrderIn
    {

            [JsonProperty("id")]
            public int Id { get; set; }

            [JsonProperty("title")]
            public string Title { get; set; }

            [JsonProperty("value")]
            public double Value { get; set; }

            [JsonProperty("valueText")]
            public string ValueText { get; set; }

            [JsonProperty("class")]
            public string Class { get; set; }

            [JsonProperty("sortOrder")]
            public int SortOrder { get; set; }
        }

}

