// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AllOrders;

namespace AllOrders
{

    public class AddonValues2
    {

        [JsonProperty("ccCvv")]
        public string CcCvv { get; set; }

        [JsonProperty("ccExpires")]
        public string CcExpires { get; set; }

        [JsonProperty("ccIssue")]
        public string CcIssue { get; set; }

        [JsonProperty("ccNumber")]
        public string CcNumber { get; set; }

        [JsonProperty("ccOwner")]
        public string CcOwner { get; set; }

        [JsonProperty("ccStart")]
        public string CcStart { get; set; }

        [JsonProperty("ccType")]
        public string CcType { get; set; }

        [JsonProperty("customerIp")]
        public string CustomerIp { get; set; }

        [JsonProperty("downloadAbandonmentStatus")]
        public string DownloadAbandonmentStatus { get; set; }

        [JsonProperty("serviceAbandonmentStatus")]
        public string ServiceAbandonmentStatus { get; set; }
    }

}
