// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AllOrders;

namespace AllOrders
{

    public class Addresses
    {

        [JsonProperty("customer")]
        public Customer2 Customer { get; set; }

        [JsonProperty("billing")]
        public Billing Billing { get; set; }

        [JsonProperty("delivery")]
        public Delivery Delivery { get; set; }
    }

}
