// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AllOrders;

namespace AllOrders
{

    public class Attributes
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }

        [JsonProperty("price")]
        public string Price { get; set; }

        [JsonProperty("priceType")]
        public string PriceType { get; set; }

        [JsonProperty("optionId")]
        public string OptionId { get; set; }

        [JsonProperty("optionValueId")]
        public string OptionValueId { get; set; }

        [JsonProperty("combisId")]
        public string CombisId { get; set; }
    }

}
