// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AllOrders;

namespace AllOrders
{

    public class StatusHistory
    {

        [JsonProperty("statusId")]
        public string StatusId { get; set; }

        [JsonProperty("dateAdded")]
        public string DateAdded { get; set; }

        [JsonProperty("comment")]
        public string Comment { get; set; }

        [JsonProperty("customerNotified")]
        public string CustomerNotified { get; set; }
    }

}
