// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AllOrders;

namespace AllOrders
{

    public class Total
    {

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }

        [JsonProperty("valueText")]
        public string ValueText { get; set; }

        [JsonProperty("class")]
        public string Class { get; set; }

        [JsonProperty("sortOrder")]
        public string SortOrder { get; set; }
    }

}
